---
name: Graphics-Asymptote
version: v0.0.1
author:
  - 'David Mertens <dcmertens.perl+Asymptote@gmail.com>'
abstract: Perl interface to the Asymptote interpreter
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  Time::HiRes: 0
  version: 0
recommends:
  PDL: 0
configure_requires:
  Module::Build: 0.35
provides:
  Graphics::Asymptote:
    file: lib/Graphics/Asymptote.pm
    version: v0.0.1
  PDL::Graphics::Asymptote:
    file: lib/PDL/Graphics/Asymptote.pm
    version: v0.0.1
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
