---
name: Graphics-Asymptote
version: 0.0.2
author:
  - 'David Mertens <dcmertens.perl+Asymptote@gmail.com>'
abstract: Perl interface to the Asymptote interpreter
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  Time::HiRes: 0
  version: 0
recommends:
  PDL: 0
provides:
  Graphics::Asymptote:
    file: lib/Graphics/Asymptote.pm
    version: 0.0.2
  PDL::Graphics::Asymptote:
    file: lib/PDL/Graphics/Asymptote.pm
    version: 0.0.2
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
